2022-01-07 17:49:09: 2022-01-07 17:49:09,019 - apscheduler.scheduler - INFO - Scheduler started
2022-01-07 17:49:10: 2022-01-07 17:49:10,014 - __main__ - INFO - Telegram shell bot started.
2022-01-07 17:49:34: 2022-01-07 17:49:34,902 - __main__ - WARNING - Update "{'update_id': 21244307, 'message': {'new_chat_members': [], 'date': 1641548974, 'group_chat_created': False, 'new_chat_photo': [], 'chat': {'id': -612110663, 'type': 'group', 'all_members_are_administrators': True, 'title': 'alpha'}, 'photo': [], 'delete_chat_photo': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'caption_entities': [], 'reply_to_message': {'new_chat_members': [], 'date': 1641548951, 'group_chat_created': False, 'new_chat_photo': [], 'chat': {'id': -612110663, 'type': 'group', 'all_members_are_administrators': True, 'title': 'alpha'}, 'photo': [], 'delete_chat_photo': False, 'reply_markup': {'inline_keyboard': [[{'callback_data': 'pwd', 'text': 'pwd'}, {'callback_data': 'ls', 'text': 'ls'}], [{'callback_data': 'pm2 list -m', 'text': '策略列表'}, {'callback_data': 'pm2 logs --nostream --lines 10', 'text': '日志'}], [{'callback_data': 'python util.py', 'text': '一键清仓!!!'}]]}, 'supergroup_chat_created': False, 'channel_chat_created': False, 'caption_entities': [], 'entities': [{'length': 6, 'offset': 7, 'type': 'bot_command'}, {'length': 5, 'offset': 19, 'type': 'bot_command'}, {'length': 14, 'offset': 32, 'type': 'bot_command'}, {'length': 13, 'offset': 56, 'type': 'bot_command'}, {'length': 15, 'offset': 80, 'type': 'bot_command'}, {'length': 14, 'offset': 115, 'type': 'bot_command'}, {'length': 17, 'offset': 149, 'type': 'bot_command'}, {'length': 9, 'offset': 185, 'type': 'bot_command'}], 'text': '支持的命令:\n/tasks 查看任务\n/kill kill任务\n/list_strategy  查询策略列表 \n/list_account   查询账户列表 \n/start_strategy  id 启动策略 参数id/name\n/stop_strategy id  停止策略 参数id/name\n/restart_strategy id 重启策略 参数id/name\n/clearpos 清仓 参数:账户id|清仓比例\n快捷键:', 'message_id': 9, 'from': {'username': 'gary_trade_02_bot', 'id': 5042431790, 'first_name': 'Gary', 'is_bot': True}}, 'entities': [{'length': 6, 'offset': 0, 'type': 'bot_command'}], 'text': '/tasks', 'message_id': 10, 'from': {'id': 5095949480, 'first_name': 'Gary', 'last_name': 'Wong', 'is_bot': False}}}" caused error "module 'delegator' has no attribute 'run'"
2022-01-07 17:49:50: 2022-01-07 17:49:50,752 - __main__ - WARNING - Update "{'update_id': 21244309, 'message': {'new_chat_members': [], 'date': 1641548990, 'group_chat_created': False, 'new_chat_photo': [], 'chat': {'id': -612110663, 'type': 'group', 'all_members_are_administrators': True, 'title': 'alpha'}, 'photo': [], 'delete_chat_photo': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'caption_entities': [], 'reply_to_message': {'new_chat_members': [], 'date': 1641548951, 'group_chat_created': False, 'new_chat_photo': [], 'chat': {'id': -612110663, 'type': 'group', 'all_members_are_administrators': True, 'title': 'alpha'}, 'photo': [], 'delete_chat_photo': False, 'reply_markup': {'inline_keyboard': [[{'callback_data': 'pwd', 'text': 'pwd'}, {'callback_data': 'ls', 'text': 'ls'}], [{'callback_data': 'pm2 list -m', 'text': '策略列表'}, {'callback_data': 'pm2 logs --nostream --lines 10', 'text': '日志'}], [{'callback_data': 'python util.py', 'text': '一键清仓!!!'}]]}, 'supergroup_chat_created': False, 'channel_chat_created': False, 'caption_entities': [], 'entities': [{'length': 6, 'offset': 7, 'type': 'bot_command'}, {'length': 5, 'offset': 19, 'type': 'bot_command'}, {'length': 14, 'offset': 32, 'type': 'bot_command'}, {'length': 13, 'offset': 56, 'type': 'bot_command'}, {'length': 15, 'offset': 80, 'type': 'bot_command'}, {'length': 14, 'offset': 115, 'type': 'bot_command'}, {'length': 17, 'offset': 149, 'type': 'bot_command'}, {'length': 9, 'offset': 185, 'type': 'bot_command'}], 'text': '支持的命令:\n/tasks 查看任务\n/kill kill任务\n/list_strategy  查询策略列表 \n/list_account   查询账户列表 \n/start_strategy  id 启动策略 参数id/name\n/stop_strategy id  停止策略 参数id/name\n/restart_strategy id 重启策略 参数id/name\n/clearpos 清仓 参数:账户id|清仓比例\n快捷键:', 'message_id': 9, 'from': {'username': 'gary_trade_02_bot', 'id': 5042431790, 'first_name': 'Gary', 'is_bot': True}}, 'entities': [{'length': 14, 'offset': 0, 'type': 'bot_command'}], 'text': '/list_strategy', 'message_id': 13, 'from': {'id': 5095949480, 'first_name': 'Gary', 'last_name': 'Wong', 'is_bot': False}}}" caused error "module 'delegator' has no attribute 'run'"
2022-01-07 19:10:56: 2022-01-07 19:10:56,131 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-01-07 19:10:56: 2022-01-07 19:10:56,131 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-01-07 19:11:08: 2022-01-07 19:11:08,323 - apscheduler.scheduler - INFO - Scheduler started
2022-01-07 19:11:09: 2022-01-07 19:11:09,315 - __main__ - INFO - Telegram shell bot started.
2022-01-07 19:11:24: 2022-01-07 19:11:24,663 - __main__ - WARNING - Update "{'message': {'text': '/list_account', 'message_id': 20, 'group_chat_created': False, 'photo': [], 'delete_chat_photo': False, 'new_chat_photo': [], 'date': 1641553882, 'channel_chat_created': False, 'caption_entities': [], 'new_chat_members': [], 'reply_to_message': {'text': '支持的命令:\n/tasks 查看任务\n/kill kill任务\n/list_strategy  查询策略列表 \n/list_account   查询账户列表 \n/start_strategy  id 启动策略 参数id/name\n/stop_strategy id  停止策略 参数id/name\n/restart_strategy id 重启策略 参数id/name\n/clearpos 清仓 参数:账户id|清仓比例\n快捷键:', 'message_id': 19, 'group_chat_created': False, 'photo': [], 'delete_chat_photo': False, 'new_chat_photo': [], 'date': 1641553879, 'channel_chat_created': False, 'caption_entities': [], 'new_chat_members': [], 'reply_markup': {'inline_keyboard': [[{'text': 'pwd', 'callback_data': 'pwd'}, {'text': 'ls', 'callback_data': 'ls'}], [{'text': '策略列表', 'callback_data': 'pm2 list -m'}, {'text': '日志', 'callback_data': 'pm2 logs --nostream --lines 10'}], [{'text': '一键清仓!!!', 'callback_data': 'python util.py'}]]}, 'chat': {'type': 'group', 'all_members_are_administrators': True, 'id': -612110663, 'title': 'alpha'}, 'supergroup_chat_created': False, 'entities': [{'offset': 7, 'type': 'bot_command', 'length': 6}, {'offset': 19, 'type': 'bot_command', 'length': 5}, {'offset': 32, 'type': 'bot_command', 'length': 14}, {'offset': 56, 'type': 'bot_command', 'length': 13}, {'offset': 80, 'type': 'bot_command', 'length': 15}, {'offset': 115, 'type': 'bot_command', 'length': 14}, {'offset': 149, 'type': 'bot_command', 'length': 17}, {'offset': 185, 'type': 'bot_command', 'length': 9}], 'from': {'is_bot': True, 'id': 5042431790, 'username': 'gary_trade_02_bot', 'first_name': 'Gary'}}, 'chat': {'type': 'group', 'all_members_are_administrators': True, 'id': -612110663, 'title': 'alpha'}, 'supergroup_chat_created': False, 'entities': [{'offset': 0, 'type': 'bot_command', 'length': 13}], 'from': {'is_bot': False, 'id': 5095949480, 'last_name': 'Wong', 'first_name': 'Gary'}}, 'update_id': 21244313}" caused error "Message text is empty"
2022-01-07 19:11:29: 2022-01-07 19:11:29,243 - __main__ - WARNING - Update "{'message': {'text': '/list_account', 'message_id': 21, 'group_chat_created': False, 'photo': [], 'delete_chat_photo': False, 'new_chat_photo': [], 'date': 1641553887, 'channel_chat_created': False, 'caption_entities': [], 'new_chat_members': [], 'reply_to_message': {'text': '支持的命令:\n/tasks 查看任务\n/kill kill任务\n/list_strategy  查询策略列表 \n/list_account   查询账户列表 \n/start_strategy  id 启动策略 参数id/name\n/stop_strategy id  停止策略 参数id/name\n/restart_strategy id 重启策略 参数id/name\n/clearpos 清仓 参数:账户id|清仓比例\n快捷键:', 'message_id': 19, 'group_chat_created': False, 'photo': [], 'delete_chat_photo': False, 'new_chat_photo': [], 'date': 1641553879, 'channel_chat_created': False, 'caption_entities': [], 'new_chat_members': [], 'reply_markup': {'inline_keyboard': [[{'text': 'pwd', 'callback_data': 'pwd'}, {'text': 'ls', 'callback_data': 'ls'}], [{'text': '策略列表', 'callback_data': 'pm2 list -m'}, {'text': '日志', 'callback_data': 'pm2 logs --nostream --lines 10'}], [{'text': '一键清仓!!!', 'callback_data': 'python util.py'}]]}, 'chat': {'type': 'group', 'all_members_are_administrators': True, 'id': -612110663, 'title': 'alpha'}, 'supergroup_chat_created': False, 'entities': [{'offset': 7, 'type': 'bot_command', 'length': 6}, {'offset': 19, 'type': 'bot_command', 'length': 5}, {'offset': 32, 'type': 'bot_command', 'length': 14}, {'offset': 56, 'type': 'bot_command', 'length': 13}, {'offset': 80, 'type': 'bot_command', 'length': 15}, {'offset': 115, 'type': 'bot_command', 'length': 14}, {'offset': 149, 'type': 'bot_command', 'length': 17}, {'offset': 185, 'type': 'bot_command', 'length': 9}], 'from': {'is_bot': True, 'id': 5042431790, 'username': 'gary_trade_02_bot', 'first_name': 'Gary'}}, 'chat': {'type': 'group', 'all_members_are_administrators': True, 'id': -612110663, 'title': 'alpha'}, 'supergroup_chat_created': False, 'entities': [{'offset': 0, 'type': 'bot_command', 'length': 13}], 'from': {'is_bot': False, 'id': 5095949480, 'last_name': 'Wong', 'first_name': 'Gary'}}, 'update_id': 21244314}" caused error "Message text is empty"
2022-01-07 19:11:41: 2022-01-07 19:11:41,603 - __main__ - WARNING - Update "{'message': {'text': '/list_account', 'message_id': 22, 'group_chat_created': False, 'photo': [], 'delete_chat_photo': False, 'new_chat_photo': [], 'date': 1641553899, 'channel_chat_created': False, 'caption_entities': [], 'new_chat_members': [], 'chat': {'type': 'group', 'all_members_are_administrators': True, 'id': -612110663, 'title': 'alpha'}, 'supergroup_chat_created': False, 'entities': [{'offset': 0, 'type': 'bot_command', 'length': 13}], 'from': {'is_bot': False, 'id': 5095949480, 'last_name': 'Wong', 'first_name': 'Gary'}}, 'update_id': 21244315}" caused error "Message text is empty"
2022-01-07 19:11:52: 2022-01-07 19:11:52,355 - __main__ - WARNING - Update "{'message': {'text': '/list_account', 'message_id': 23, 'group_chat_created': False, 'photo': [], 'delete_chat_photo': False, 'new_chat_photo': [], 'date': 1641553910, 'channel_chat_created': False, 'caption_entities': [], 'new_chat_members': [], 'chat': {'type': 'group', 'all_members_are_administrators': True, 'id': -612110663, 'title': 'alpha'}, 'supergroup_chat_created': False, 'entities': [{'offset': 0, 'type': 'bot_command', 'length': 13}], 'from': {'is_bot': False, 'id': 5095949480, 'last_name': 'Wong', 'first_name': 'Gary'}}, 'update_id': 21244316}" caused error "Message text is empty"
2022-01-07 19:14:26: 2022-01-07 19:14:26,285 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-01-07 19:14:26: 2022-01-07 19:14:26,285 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-01-07 19:14:33: 2022-01-07 19:14:33,125 - apscheduler.scheduler - INFO - Scheduler started
2022-01-07 19:14:34: 2022-01-07 19:14:34,104 - __main__ - INFO - Telegram shell bot started.
2022-01-07 19:14:43: 2022-01-07 19:14:43,951 - __main__ - WARNING - Update "{'update_id': 21244317, 'message': {'text': '/list_account', 'supergroup_chat_created': False, 'new_chat_members': [], 'entities': [{'length': 13, 'offset': 0, 'type': 'bot_command'}], 'delete_chat_photo': False, 'date': 1641554081, 'caption_entities': [], 'photo': [], 'group_chat_created': False, 'channel_chat_created': False, 'chat': {'id': -612110663, 'title': 'alpha', 'all_members_are_administrators': True, 'type': 'group'}, 'new_chat_photo': [], 'message_id': 24, 'from': {'first_name': 'Gary', 'is_bot': False, 'id': 5095949480, 'last_name': 'Wong'}}}" caused error "Message text is empty"
2022-01-07 19:15:01: 2022-01-07 19:15:01,212 - __main__ - WARNING - Update "{'update_id': 21244318, 'message': {'text': '/list_strategy', 'supergroup_chat_created': False, 'new_chat_members': [], 'entities': [{'length': 14, 'offset': 0, 'type': 'bot_command'}], 'delete_chat_photo': False, 'date': 1641554101, 'caption_entities': [], 'photo': [], 'reply_to_message': {'text': '支持的命令:\n/tasks 查看任务\n/kill kill任务\n/list_strategy  查询策略列表 \n/list_account   查询账户列表 \n/start_strategy  id 启动策略 参数id/name\n/stop_strategy id  停止策略 参数id/name\n/restart_strategy id 重启策略 参数id/name\n/clearpos 清仓 参数:账户id|清仓比例\n快捷键:', 'supergroup_chat_created': False, 'new_chat_members': [], 'entities': [{'length': 6, 'offset': 7, 'type': 'bot_command'}, {'length': 5, 'offset': 19, 'type': 'bot_command'}, {'length': 14, 'offset': 32, 'type': 'bot_command'}, {'length': 13, 'offset': 56, 'type': 'bot_command'}, {'length': 15, 'offset': 80, 'type': 'bot_command'}, {'length': 14, 'offset': 115, 'type': 'bot_command'}, {'length': 17, 'offset': 149, 'type': 'bot_command'}, {'length': 9, 'offset': 185, 'type': 'bot_command'}], 'delete_chat_photo': False, 'date': 1641553879, 'caption_entities': [], 'photo': [], 'group_chat_created': False, 'channel_chat_created': False, 'chat': {'id': -612110663, 'title': 'alpha', 'all_members_are_administrators': True, 'type': 'group'}, 'new_chat_photo': [], 'reply_markup': {'inline_keyboard': [[{'text': 'pwd', 'callback_data': 'pwd'}, {'text': 'ls', 'callback_data': 'ls'}], [{'text': '策略列表', 'callback_data': 'pm2 list -m'}, {'text': '日志', 'callback_data': 'pm2 logs --nostream --lines 10'}], [{'text': '一键清仓!!!', 'callback_data': 'python util.py'}]]}, 'message_id': 19, 'from': {'username': 'gary_trade_02_bot', 'first_name': 'Gary', 'is_bot': True, 'id': 5042431790}}, 'group_chat_created': False, 'channel_chat_created': False, 'chat': {'id': -612110663, 'title': 'alpha', 'all_members_are_administrators': True, 'type': 'group'}, 'new_chat_photo': [], 'message_id': 25, 'from': {'first_name': 'Gary', 'is_bot': False, 'id': 5095949480, 'last_name': 'Wong'}}}" caused error "module 'delegator' has no attribute 'run'"
2022-01-07 19:16:00: 2022-01-07 19:16:00,426 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-01-07 19:16:00: 2022-01-07 19:16:00,426 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-01-07 19:16:07: 2022-01-07 19:16:07,226 - apscheduler.scheduler - INFO - Scheduler started
2022-01-07 19:16:08: 2022-01-07 19:16:08,201 - __main__ - INFO - Telegram shell bot started.
2022-01-09 22:00:57: 2022-01-09 22:00:45,024 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-09 22:00:57: 2022-01-09 22:00:45,093 - __main__ - WARNING - Update "None" caused error "urllib3 HTTPError ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
2022-01-23 09:10:25: 2022-01-23 09:10:25,876 - telegram.ext.updater - ERROR - Error while getting Updates: Bad Gateway
2022-01-23 09:10:25: 2022-01-23 09:10:25,876 - __main__ - WARNING - Update "None" caused error "Bad Gateway"
2022-02-01 05:07:28: 2022-02-01 05:07:28,378 - telegram.ext.updater - ERROR - Error while getting Updates: Bad Gateway
2022-02-01 05:07:28: 2022-02-01 05:07:28,379 - __main__ - WARNING - Update "None" caused error "Bad Gateway"
2022-02-19 09:10:15: 2022-02-19 09:10:15,178 - telegram.ext.updater - ERROR - Error while getting Updates: Bad Gateway
2022-02-19 09:10:15: 2022-02-19 09:10:15,179 - __main__ - WARNING - Update "None" caused error "Bad Gateway"
2022-02-25 02:05:11: 2022-02-25 02:05:11,318 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-02-25 02:05:11: 2022-02-25 02:05:11,322 - __main__ - WARNING - Update "None" caused error "urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
2022-03-03 13:36:25: 2022-03-03 13:36:25,071 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-03-03 13:36:25: 2022-03-03 13:36:25,071 - __main__ - WARNING - Update "None" caused error "urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
2022-03-14 22:02:59: 2022-03-14 22:02:59,652 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-03-14 22:02:59: 2022-03-14 22:02:59,653 - __main__ - WARNING - Update "None" caused error "urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
2022-03-18 09:10:18: 2022-03-18 09:10:18,040 - telegram.ext.updater - ERROR - Error while getting Updates: Bad Gateway
2022-03-18 09:10:18: 2022-03-18 09:10:18,041 - __main__ - WARNING - Update "None" caused error "Bad Gateway"
2022-03-24 16:53:06: 2022-03-24 16:53:06,340 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-03-24 16:53:06: 2022-03-24 16:53:06,340 - __main__ - WARNING - Update "None" caused error "urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
2022-03-29 09:00:38: 2022-03-29 09:00:38,002 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-03-29 09:00:38: 2022-03-29 09:00:38,003 - __main__ - WARNING - Update "None" caused error "urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
2022-04-10 09:10:18: 2022-04-10 09:10:18,318 - telegram.ext.updater - ERROR - Error while getting Updates: Bad Gateway
2022-04-10 09:10:18: 2022-04-10 09:10:18,319 - __main__ - WARNING - Update "None" caused error "Bad Gateway"
2022-04-16 21:16:35: 2022-04-16 21:16:35,553 - telegram.ext.updater - ERROR - Error while getting Updates: Bad Gateway
2022-04-16 21:16:35: 2022-04-16 21:16:35,553 - __main__ - WARNING - Update "None" caused error "Bad Gateway"
2022-04-18 06:39:35: 2022-04-18 06:39:35,945 - telegram.ext.updater - ERROR - Error while getting Updates: Bad Gateway
2022-04-18 06:39:35: 2022-04-18 06:39:35,946 - __main__ - WARNING - Update "None" caused error "Bad Gateway"
2022-04-21 20:39:40: 2022-04-21 20:39:40,600 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-04-21 20:39:40: 2022-04-21 20:39:40,601 - __main__ - WARNING - Update "None" caused error "urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
2022-04-21 20:40:32: 2022-04-21 20:40:32,563 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-04-21 20:40:32: 2022-04-21 20:40:32,563 - __main__ - WARNING - Update "None" caused error "urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
2022-05-05 07:08:38: 2022-05-05 07:08:38,390 - telegram.ext.updater - ERROR - Error while getting Updates: Bad Gateway
2022-05-05 07:08:38: 2022-05-05 07:08:38,391 - __main__ - WARNING - Update "None" caused error "Bad Gateway"
2022-05-05 17:16:49: 2022-05-05 17:16:49,323 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-05-05 17:16:49: 2022-05-05 17:16:49,324 - apscheduler.scheduler - INFO - Scheduler has been shut down
